### ISSUE TITLE
[Bug]predict出的路径第一步都不是O，而是I_PER或者I_ORG

### ISSUE THREAD

**Issue by liuyijiang1994** [circlePi/Bert_Chinese_Ner_pytorch#3]
使用作者提供的代码和下载的数据训练3轮之后，使用训练集验证的结果为：

               precision    recall  f1-score   support
           0       0.98      0.88      0.93      2832
           1       0.65      0.98      0.78      5463
           2       0.99      0.85      0.92      3666
           3       0.99      1.00      0.99     11118
           4       0.89      0.85      0.87       321
           5       0.48      0.99      0.64       831
           6       0.99      0.99      0.99      3736
           7       0.97      0.99      0.98      5856
           8       1.00      0.99      0.99    292838
          accuracy                           0.99    326661
          macro avg       0.88      0.94      0.90    326661
          weighted avg       0.99      0.99      0.99    326661

可以很明显的发现，1和5两个label的precision明显比其他的低，但acc非常高，所以应该是多判断了一半的label为1或者5，经过调试我发现，crf 维特比解码的结果第一步大部分不是1就是5，分别对应I_PER或者I_ORG，这是最不可能的情况，训练集中没有这种开头的sample。打印crf的transition一看start到1和5的score确实相对较高。
总结一下，就是一个第一步标签总是解码出错的bug，目前还没有排查出bug原因。

**Comment by liuyijiang1994** [comment]
我替换了一下crf实现，解决了这个问题，可能bug出在crf层。

**Comment by circlePi** [comment]
感谢提出疑问。结果中并没有看到您说的1和5的acc高，我看到的是acc低recall高。您说的大部分具体是什么比例呢，从support来看，这个比例应当很低。可以打印下混淆矩阵么，这样可以看得更清楚些。

**Comment by circlePi** [comment]
@liuyijiang1994 您好，我重跑了一边代码，并没有出现您说的情况，结果如下：
classify_report:
              precision    recall  f1-score   support

          0       0.98      0.97      0.98     43652
          1       0.98      0.98      0.98     84099
          2       1.00      1.00      1.00     43323
          3       1.00      1.00      1.00    117899
          4       0.96      0.88      0.92      3569
          5       0.86      0.99      0.92      7847
          6       0.99      0.99      0.99     49667
          7       0.98      0.99      0.99     78875
          8       1.00      1.00      1.00   4055215

avg / total       1.00      1.00      1.00   4484146

[2019-09-13 07:38:39]: torch train.py[line:155] INFO  
Epoch 2 - train_loss: 0.047266 - eval_loss: 0.037106 - train_acc:0.997468 - eval_acc:0.997581 - eval_f1:0.973249
可能是您数据的问题，请仔细核查下。

**Comment by liuyijiang1994** [comment]
@circlePi  多谢！我再检查一遍！

**Comment by Ian-peace** [comment]
> 我替换了一下crf实现，解决了这个问题，可能bug出在crf层。
请问你是如何替换的？我也出现了这个问题
