### ISSUE TITLE
The corresponding binary is missing, causing the model to fail to load.

### ISSUE THREAD

**Issue by jlu-phyComputer** [circlePi/Bert_Chinese_Ner_pytorch#4]
The corresponding binary file is missing, causing the model to fail to load.

**Comment by hertz-pj** [comment]
不是很理解，请问为什么使用bert还构建了自己的字典。

**Comment by circlePi** [comment]
> The corresponding binary file is missing, causing the model to fail to load.

这段有点短的不能说明问题，我猜想是BERT模型缺失。如果是的话，下载下转换成pytorch格式放在model文件夹即可

**Comment by circlePi** [comment]
> 不是很理解，请问为什么使用bert还构建了自己的字典。

你的想法是对的，建立字典这段代码事实上目前没有用到。
