### ISSUE TITLE
为什么我的无法加载这个库（小白一个）

### ISSUE THREAD

**Issue by CerryXu** [circlePi/Bert_Chinese_Ner_pytorch#5]
![FYV47_6A4J`$6_RQM2{F~~S](https://user-images.githubusercontent.com/45084662/68079954-3fdde180-fe2d-11e9-8f50-e98517f5297f.jpg)

**Comment by circlePi** [comment]
您可以用命令行import一下看看是否只是pycharm没有同步的原因。如果还没有，建议重新安装下pytorch
