### ISSUE TITLE
请问数据的格式应该是什么样子的？

### ISSUE THREAD

**Issue by Ian-peace** [circlePi/Bert_Chinese_Ner_pytorch#8]

**Comment by Ian-peace** [comment]
就是训练数据和测试数据的格式，应该如何命名？

**Comment by Ian-peace** [comment]
![image](https://user-images.githubusercontent.com/26326751/69602428-83a1c080-1052-11ea-9b51-184b72766383.png)
还有，bert-chinese包里面有这五个文件，把前面四个都放在pytorch_pretrained_model/目录下就可以嘛？

**Comment by Ian-peace** [comment]
![image](https://user-images.githubusercontent.com/26326751/69607013-468ffb00-105f-11ea-9e04-e3563d7679e4.png)
还有就是 这个是什么文件啊？

**Comment by Ian-peace** [comment]
抱歉哦，还有两个问题：

**Comment by Ian-peace** [comment]
抱歉哦，还有两个问题：
1、如果我原本就已经分好了训练集和验证集还有测试集，我应该怎么修改代码？
2、我如果测试已经训练好的模型？并且如何去用？当前的代码是只能训练嘛？

**Comment by circlePi** [comment]
1. 如果有了分好的train dev，您需要注释掉preprocessing/data_processor.py中的一些内容。如果不清楚要怎么改，可以下载我提供的数据，看下中间过程。看最终输入到模型的是什么格式，只要处理成那种格式就可以了。
2. 预测的代码我抽空上传一下。目前的只支持训练。
其他：
WEIGHTS_NAME是bert模型的名称。
命名：与config/args.py中保持一致即可。
目录：您需要将原始的tensorflow权重文件转换成pytorch格式。

**Comment by Ian-peace** [comment]
好的，谢谢。
代码现在还存在一个问题就是，CRF层约束 模型好像没有学习到，它会在实体开头输出 I 标签

**Comment by Ian-peace** [comment]
并且开头是 I 标签的 都是I-PER标签
